### ISSUE TITLE
Autolock timer does not work after STR

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-lockwise/lockwise-ios#1002]
Build: 1.6.0(3339)
Device: iPhone Xr
iOS: 12.2

Preconditions:
- Biometrics to unlock enabled

Steps to reproduce:
1. Launch Lockwise
2. Unlock Lockwise
3. Lock the device while app is in foreground (wait the amount of time it's need in order for the app to lock)
4. Unlock the device -> The app will be unlocked
5. Backround the app and lock the device
6. Wait the amount of time it's need in order for the app to lock
7. Unlock the device
8. Open the app

Actual results:
- The app will be unlocked.

**Comment by sashei** [comment]
We've removed locking in the foreground on iOS as of #916.

**Comment by SimonBasca** [comment]
@sashei shouln't the app autolock after step 5) and 6) ?

**Comment by sashei** [comment]
@SimonBasca clearly a distracted close!! Thank you for following up. Yes, it should lock the app.
