### ISSUE TITLE
Unable to unlock app without internet connection

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-lockwise/lockwise-ios#1004]
Build: 1.6.0(3339)
Device: iPhone Xr
iOS: 12.0

Precondition
- Biometrics to unlock enabled

Steps to reproduce:
1.  Lock and close the app
2. Turn off internet connection
3. Launch the app
4. Tap the Unlock button

Actual results:
- Unlocking the app is not possible without internet connection. The "Unlock" button does not prompt biometrics to unlock the app.

**Comment by csuciu** [comment]
After following the STR and then re-connect to internet, the app still cannot be unlocked until it is restarted.
