### ISSUE TITLE
(Spanish) Localization issues

### ISSUE THREAD

**Issue by isabelrios** [mozilla-lockwise/lockwise-ios#1014]
There are some issues with the Spanish translation:
1-Recently Used is not correctly translated. It should be `recientemente`
![IMG_235F4C80B424-1](https://user-images.githubusercontent.com/1897507/58315811-848f3680-7e12-11e9-925d-ba702e3995ea.jpeg)

2- When entries are sorted by Recent, the name in the button is shown with ellipsis in the middle, it does not look nice :/ 
![IMG_3CFB2607AD3D-1](https://user-images.githubusercontent.com/1897507/58315782-75a88400-7e12-11e9-9bd1-cb9e2d09a7b6.jpeg)

**Comment by isabelrios** [comment]
3- Username and Password copied message is not correct.
For Username it is cut: it should be `Nombre de usuario copiado`. And for Password, `Contraseña copiada`
![IMG_2891](https://user-images.githubusercontent.com/1897507/58317641-7e9b5480-7e16-11e9-9692-a47749d2bf4a.PNG)
![IMG_2892](https://user-images.githubusercontent.com/1897507/58317646-80fdae80-7e16-11e9-86f4-a6eb0c8c772a.PNG)

**Comment by isabelrios** [comment]
4- The screen to enter the password when logging in is not correct:
![iPhone X-16PasswordScreenUICTContentSizeCategoryL](https://user-images.githubusercontent.com/1897507/58323193-8ca3a200-7e23-11e9-8dac-6a7a1b73900c.png)

**Comment by sashei** [comment]
@rfk do we have any way to translate the FxA login? I assume this is an issue across all of the languages we are aiming to support in lockwise.
