### ISSUE TITLE
Logins "Blank State" Due to FxA Dismissal

### ISSUE THREAD

**Issue by changecourse** [mozilla-lockwise/lockwise-ios#1024]
I'm unable to access my logins on 1.6.0, due to the FxA Sign-in code prompting, but dismissing once the app is backgrounded in order to go fetch the code within my mail client. This results in the webview being closed, landing on the login list, but there being no error message or indication of any logins associated with my account (and endless spinning from manual sync trigger)

Steps to Reproduce:
1.  Install fresh build from app store and launch app
2. tap get started
3. FxA: enter email address
4. FxA: enter password
5. FxA: presented with request for code, I backgrounded the app to go to my mail client
6. Upon fetching the code and returning to the app, the FxA prompt had been dismissed, and I ended up in the blank state, unable to view my logins. My account info is not displayed in "My Account" and disconnecting/restarting leads me through the same set of steps.

Device: iPhone Xs, 12.2

**Comment by devinreams** [comment]
Hmm I can't reproduce this. 🤔 

- if I background the app and open mail and return it stays on the FxA confirmation code screen (to try and recreate your scenario)
- if I background the app and open 10 other apps, then return, it stays on the FxA confirmation code screen (simulate running out of resources or similar)
- if I background the app and wait 5 minutes, then return, it stays on the FxA confirmation code screen (simulate an autolock or similar)
- if I force quit the app and return it takes me back to the "Get Started" state

**Comment by devinreams** [comment]
OK we got another report from Porfirio encountering this backgrounding "blank" state.

@sashei does your last PR #1023 potentially help with this? worth sending a TestFlight build ASAP to see if still happening to these folks?

**Comment by sashei** [comment]
@devinreams possibly, let's try that out.

**Comment by sashei** [comment]
@devinreams otherwise I think we have enough reports & this is a bad enough issue to justify uplifting / investigating independently! curious to hear what folks say about the new code though.

**Comment by SimonBasca** [comment]
I was able to reproduce this on a iPhone Xr (12.2) only once with my personal account. The only difference from the flow in the description was that at step 5) I received the email confirmation. After being in the "Blank State" restarting the app directed me to the Welcome screen and everything worked as expected with the same flow in the description.

I'll try to reproduce again and add more info if I find reliable steps.

**Comment by devinreams** [comment]
@changecourse with the latest TestPilot build (1.6.1) are you seeing the same still?


>After being in the "Blank State" restarting the app directed me to the Welcome screen

@SimonBasca and "Restarting" means force quit not just backgrounding, right?

**Comment by SimonBasca** [comment]
@devinreams, yes. Force quitting from app switcher and re-launching.

**Comment by changecourse** [comment]
@devinreams confirmed and tested build 3457, 1.6.1.

Let me sign in without needing to confirm via email/enter code... I feel like my account is in some sort of weird purgatory where I didn’t truly get a token or something the first time around, and now it’ll let me successfully authenticate but then it doesn’t actually fetch my logins.

Additional sleuthing reveals something else strange... instances of me trying to authenticate Lockwise show up as a generic “web session” under devices and apps for FxA. Revoking web sessions and disconnecting/reauthenticating still don’t issue a new token potentially, nor can I get Lockwise to show up as an app in FxA

**Comment by devinreams** [comment]
>Let me sign in without needing to confirm via email/enter code... I feel like my account is in some sort of weird purgatory where I didn’t truly get a token or something the first time around, and now it’ll let me successfully authenticate but then it doesn’t actually fetch my logins.

My wife was experiencing similar, and today with the 1.6.1 update: after signing in again she was dropped into a working list. What if you Account>Disconnect once more and then sign in again?

>Additional sleuthing reveals something else strange... instances of me trying to authenticate Lockwise show up as a generic “web session”

Good sleuthing but that's likely unrelated as it's been known issue on the FxA side since.. forever?

**Comment by changecourse** [comment]
>My wife was experiencing similar, and today with the 1.6.1 update: after signing in again she was dropped into a working list. What if you Account>Disconnect once more and then sign in again?

Disconnected and reconnected, app asked for sign-in code, still no logins found. 

Then I disconnected, deleted app, reinstalled, and reauthenticated... still no logins.

**Comment by sashei** [comment]
@devinreams @changecourse what's the story with this issue? do we want to close now that @changecourse has deleted all his passwords ?

**Comment by changecourse** [comment]
There's certainly still an issue involving "No Logins Found" independent of FxA routing, though it may be more-so with application-services than with our code base... Not sure how to track/escalate/surface up the work, but I feel a problem certainly still exists for a large portion of users.

**Comment by tonglil** [comment]
I believe I am getting this issue.
My Firefox account has MFA and this is my flow:
- enter email
- enter password
- switch to another app for mfa code
- paste mfa
- login success
- screen is forever "no logins found", even after syncing multiple days, and multiple re-login and re-installs later

**Comment by devinreams** [comment]
We have an updated release candidate for [version 1.6.2](https://github.com/mozilla-lockwise/lockwise-ios/releases/tag/1.6.2.3598) on TestFlight.

Anyone should feel free to opt-in and help us test it using this link: 
https://testflight.apple.com/join/AoGdcFaW

Thank you very much!

**Comment by devinreams** [comment]
The 1.6.2 release is going out with on a phased schedule. If you encounter this again please let us know.
