### ISSUE TITLE
Translated strings don't wrap on autofill instruction or item detail screens

### ISSUE THREAD

**Issue by devinreams** [mozilla-lockwise/lockwise-ios#1029]
Spotted in German:

- [x] Autofill instructions go to the end of the screen
  ![image](https://user-images.githubusercontent.com/49511/58578282-a8cd8780-8205-11e9-870a-a631785693cf.png)

- [x] Item entry detail "Learn how to edit" link at the bottom does not wrap
  ![image](https://user-images.githubusercontent.com/49511/58578264-9eab8900-8205-11e9-8db3-df9e5418fe54.png)

- [x] Entry list link to learn more beneath "no matches found"

**Comment by isabelrios** [comment]
There is one more thing in German I saw, the string `Learn more`when there are no matches when searching for users. It overlaps the `>`icon:
![Screenshot 2019-05-29 at 19 45 58](https://user-images.githubusercontent.com/1897507/58579053-84e06500-824a-11e9-8d85-90eaeb609074.png)
