### ISSUE TITLE
In french the text is cut (minor)

### ISSUE THREAD

**Issue by usercase** [mozilla-lockwise/lockwise-ios#1040]
![lockwise](https://user-images.githubusercontent.com/45983715/58747293-702de800-8469-11e9-8c16-46fd48c24071.PNG)

1. The end of the text is missing
2. There should a right and left margin

**Comment by devinreams** [comment]
Thanks for the report, @usercase! You should see this fixed with the latest app update version 1.6.1. 

Fixed at #1030
