### ISSUE TITLE
l10n: AutoFill Cancel button appears with ellipsis in the middle

### ISSUE THREAD

**Issue by isabelrios** [mozilla-lockwise/lockwise-ios#1047]
Steps:
Go to anywebsite to log in and select Lockbox to use your passwords

Actual
The Cancel text is not shown fine

Expected
The text should be `Cancelar`or something that is readable but not cut in the middle

Please see screenshot:
![IMG_3010](https://user-images.githubusercontent.com/1897507/59104136-031ac680-8931-11e9-886d-2984b818209a.PNG)

**Comment by devinreams** [comment]
Ah this is also true for German (de): "Abbrechen" doesn't fit.

Thanks for the report @isabelrios

**Comment by SimonBasca** [comment]
Verifying as fix on 1.6.2 (3598)
