### ISSUE TITLE
[l10nScreensthosTests] Add new tests for the Delete feature

### ISSUE THREAD

**Issue by isabelrios** [mozilla-lockwise/lockwise-ios#1076]
This issue is to add the necessary tests to check the new strings added for the Delete feature.

**Comment by isabelrios** [comment]
@joeyg, @devinreams, @ddurst I guess you are aware of this menu not translated yet, but just to be sure this is tracked someplace...if not, please let me know so that I can file an issue. Thanks!
![Screenshot 2019-07-02 at 13 44 11](https://user-images.githubusercontent.com/1897507/60510382-91cff880-9ccf-11e9-865c-487f96e91fcb.png)

**Comment by devinreams** [comment]
Thanks @isabelrios, these strings should get pulled into Pontoon with the next manual export we run and then manually imported once translated. :+1:
