### ISSUE TITLE
Telemetry action for `settingsProvideFeedback` no longer exists

### ISSUE THREAD

**Issue by irrationalagent** [mozilla-lockwise/lockwise-ios#1087]
Once upon a time we had an action for the provide feedback button/form, so we could record telemetry for it. But I think it disappeared a long time ago.

https://github.com/mozilla-lockwise/lockwise-ios/blob/19271a021c20ef71bec22b198228cd7d143974b4/lockbox-ios/Action/SettingAction.swift

We still spec for it here

https://github.com/mozilla-lockwise/lockwise-ios/blob/master/Shared/Action/TelemetryAction.swift#L42

We seem to have had telemetry for it up until about 2018-05-31: https://sql.telemetry.mozilla.org/queries/63560/source#162668

How hard would it be to add this action back? May not be worth a whole lot of re-wiring, but it would be helpful to have. 

CC @yuvalwolf

**Comment by eliserichards** [comment]
@joeyg would this be doable?

**Comment by joeyg** [comment]
@irrationalagent It appears that the `Send Feedback` link is broken. When I tap on it in settings I get taken to a webview showing mozilla.com. Is the URL here still valid? https://github.com/mozilla-lockwise/lockwise-ios/blob/master/lockbox-ios/Common/Resources/Constants.swift#L15

**Comment by irrationalagent** [comment]
@joeyg pinged you in slack, maybe @yuvalwolf or @changecourse can confirm what the right URL is supposed to be

**Comment by yuvalwolf** [comment]
URL is fixed now (and is the same as https://github.com/mozilla-lockwise/lockwise-ios/blob/master/lockbox-ios/Common/Resources/Constants.swift#L15).
