### ISSUE TITLE
Update FAQ links and Feedback to point to support.mozilla.com articles

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockwise/lockwise-ios#1093]
### Why/User Benefit/User Problem
Right now we're not able to adequately support our users well with Discourse and our obligatory email address in the app store. The Firefox Support team is stepping in to better cover our product support needs, which requires some updates on our side.

Mapping here: https://docs.google.com/spreadsheets/d/16bKy18uXTGHMAG7UVZbVRoxd_RNgKGaKtmbnR_D9LFQ/edit#gid=0

### Acceptance Criteria (how do I know when I’m done?)
* Overall UX should reflect 'new' Firefox changes coming with Fx70
* All "learn more" links should reference our support (SUMO) articles
* Should replace Feedback with "Get Support" and direct to SUMO

**Comment by jonichan** [comment]
@sandysage Here are the corresponding in-product links you can use for each article. They are in column D ("Links to use in the UI")

https://docs.google.com/spreadsheets/d/16bKy18uXTGHMAG7UVZbVRoxd_RNgKGaKtmbnR_D9LFQ/edit?usp=sharing

**Comment by changecourse** [comment]
I went through the mapping spreadsheet and added two columns, one for identifying which section of our app the current link is in, and one column to decide whether we should 'keep, remove, or add' a link based on the latest SUMO articles. 

Furthermore, I greyed out the fields that are not pertinent to our effort, so any changes will only have to be made on white background rows. 

Please reach out with any questions or concerns upon digging into the material above.

**Comment by changecourse** [comment]
@sandysage this likely needs to be elevated for iOS as the current links may be broken.

**Comment by SimonBasca** [comment]
Verifying as fix on 1.7.1 (3988). Only 2 task remain here :  #1165 and #1166
