### ISSUE TITLE
Headers not rendering correctly on iOS 13

### ISSUE THREAD

**Issue by tankmohit** [mozilla-lockwise/lockwise-ios#1097]
The UI elements on iOS 13 are broken. Please refer to the screenshot. 
![09349FFC-C3F7-4F50-9C74-9812A47F038C](https://user-images.githubusercontent.com/27958239/67306660-55feb000-f4c5-11e9-9c4f-5c4969691127.jpeg)

**Comment by lorenzhs** [comment]
In the password detail view, this causes the "back" button to be invisible because it has the same text colour as the background.

**Comment by eliserichards** [comment]
Invision link: https://mozilla.invisionapp.com/share/BQEUSO0S2#/screens/267560598_Entry_List

**Comment by SimonBasca** [comment]
Verifying as fix on iPhone X 13.2 build 3809.
