### ISSUE TITLE
Allow the "bento box" to open Lockwise if installed

### ISSUE THREAD

**Issue by ddurst** [mozilla-lockwise/lockwise-ios#1100]
The "bento box" menu was added to monitor.firefox.com last week, and the link to Lockwise should open the app if installed and open the store if not.

This has been done on Android, so I'm cutting and pasting the iOS-relevant bits here:

1. For iOS, we need to set up Universal links (full process outlined here: https://help.adjust.com/optimize/re-engagement/deeplinks/direct-links-for-ios); @lwa-moz can help with this, but there is an iOS developer component that needs completion.
2. For reference, here is the full multi-platform link creation process instructions (received from our Adjust rep returning from PTO yesterday; apologies for not providing complete instructions earlier):

   2.1. Creating a multi-platform Universal Link with a "fallback" parameter appended:
           - Implement Universal Linking into the iOS version of the app. Docs on that are [here](https://help.adjust.com/optimize/re-engagement/deeplinks/direct-links-for-ios).

   2.2. Generate the universal link in the dashboard
           - e.g. https://z9pm.adj.st/

   2.3. Include a tracker token you've generated in the dashboard to track the activity on the URL
           - e.g. https://z9pm.adj.st/?adjust_t=klm012

   2.4. Add a "deeplink=" parameter to the URL for iOS users
           - e.g. https://z9pm.adj.st/?adjust_t=klm012&deeplink=myapp%3A%2F%2Fpage

   2.5. Cap it off with a "fallback=" parameter which redirects off-platform users to another URL.
           - e.g. https://z9pm.adj.st/?adjust_t=klm012&deeplink=myapp%3A%2F%2Fpage&fallback=https%3A%2F%2Ffallback.webpage

(If any of this is boogered here and is really Android-specific, it's because I cribbed it from https://github.com/mozilla-lockwise/lockwise-android/pull/967.)

**Comment by kaylagalway** [comment]
Universal link is: https://bhqf.adj.st

**Comment by abodea** [comment]
#### Hi, I re-checked this using the latest build **`Buddybuild Build 3869`** with **`iPhone X(iOS 13.2.2)`**, for mode details please see the details below:

| Case  |Lockwise installed? |Lockwise opened?|
|------------- | :-------------: |:-------------:|
| **Open Universal URL from a Note** | Yes  | ✔️  |
| **Open Universal URL from a contact info**  | Yes   | ✔️  |
| **[Open Universal URL from a webpage](https://wiki.mozilla.org/Test/lockwise/abodea)**  | Yes  | ✔️  |
| **Open Universal URL from email** | Yes   | ✔️  |
| **[Open Universal URL from a google doc](http://tiny.cc/w35agz)** | Yes   | ✔️  |
| **Open Universal URL from a Note** | No  | ❌  |
| **Open Universal URL from a contact info**  | No  | ❌  |
| **[Open Universal URL from a webpage](https://wiki.mozilla.org/Test/lockwise/abodea)**  | No  | ❌  |
| **Open Universal URL from email** | No   | ❌  |
| **[Open Universal URL from a google doc](http://tiny.cc/w35agz)** | No   | ❌  |

- Note that when Lockwise is not installed there is always a new page opened in browser returning **`Url not found`**, this is also displayed when any other version than **`Buddybuild Build 3869`** of Lockwise is installed.
- When I accessed the Universal Link with **`Buddybuild Build 3869`**  everything worked correctly, even if I was logged in or not.

@kaylagalway @ddurst @sandysage is this link only applicable when Lockwise is installed?
I was thinking that if Lockwise is not installed, it should redirect the user to app store.

**Comment by changecourse** [comment]
>Is this link only applicable when Lockwise is installed?

No; when Lockwise is not installed, for iOS users it should take them to the app store listing.

@ddurst @kaylagalway  it sounds like the deeplink is working, but perhaps not the fallback redirect to the app store?

**Comment by kaylagalway** [comment]
Checked in with Adjust and we will need to make a slight change to the url in order for it to open the app store if the Lockwise app is not installed.  Loren will add a tracker token in the Adjust dashboard on Monday(11/18), which we need for the new url. 

The new url will be formatted like this: `https://bhqf.adj.st/?adjust_t=(tracker token here)` 

Will comment on this ticket once the update has been made.

**Comment by lwa-moz** [comment]
Link with Tracker token appended here: https://bhqf.adj.st/?adjust_t=6tteyjo

Full link with tracker token, Android deeplink, and desktop URL fallback here: https://bhqf.adj.st/?adjust_t=6tteyjo&deeplink=lockwise%3A%2F%2F&fallback=https%3A%2F%2Fwww.mozilla.org%2Fen-US%2Ffirefox%2Flockwise

We should test out the full link once the iOS update is complete.

**Comment by kaylagalway** [comment]
This can now be retested with the universal link that includes a tracker token posted by @lwa-moz above. 

It can be tested on the release build [3902](https://dashboard.buddybuild.com/apps/5a0ddb736e19370001034f85/build/5dd45fd0cf3b7100010257fb) 
[Install IPA on Device](https://downloads.buddybuild.com/download/ios?buildID=5dd45fd0cf3b7100010257fb&email=kayla.galway@gmail.com&download_token=a9017c98-ecd5-4459-9c05-96322e38736e)

Follow the same steps as noted in previous instructions:

    - Run the application on an iOS device
    - Open the Notes application
    - Create new note with the following universal link: https://bhqf.adj.st/?adjust_t=6tteyjo
    - Click that link and Lockwise should open

**Comment by SimonBasca** [comment]
@kaylagalway This was retested with the latest build 3902, on iPhone 8 (11.4), iPhone 7 (12.3), iPhone X (13.0) and iPad Pro (13.1). 

| Case  |Lockwise installed? |Results|
|------------- | :-------------: |:-------------:|
| **Open Universal URL from a Note** | Yes  | Lockwise opened  |
| **Open Universal URL from a contact info**  | Yes   | Lockwise opened  |
| **[Open Universal URL from a webpage](https://wiki.mozilla.org/Test/lockwise/abodea)**  | Yes  | Lockwise opened  |
| **Open Universal URL from email** | Yes   | Lockwise opened  |
| **[Open Universal URL from a google doc](http://tiny.cc/w35agz)** | Yes   | Lockwise opened |
| **Open Universal URL from a Note** | No  | App Store was opened and Lockwise app was presented |
| **Open Universal URL from a contact info**  | No  | App Store was opened and Lockwise app was presented  |
| **[Open Universal URL from a webpage](https://wiki.mozilla.org/Test/lockwise/abodea)**  | No | App Store was opened and Lockwise app was presented |
| **Open Universal URL from email** | No   | App Store was opened and Lockwise app was presented  |
| **[Open Universal URL from a google doc](http://tiny.cc/w35agz)** | No | App Store was opened and Lockwise app was presented |

**Comment by lesleyjanenorton** [comment]
On desktop, using this url `https://app.adjust.com/?adjust_t=6tteyjo&deeplink=lockwise%3A%2F%2F&fallback=https%3A%2F%2Fwww.mozilla.org%2Fen-US%2Ffirefox%2Flockwise` I am redirect to the App Store each time.

**Comment by lwa-moz** [comment]
I've reached out to Adjust support to help troubleshoot.

Here's the template they originally provided in case anyone can spot the mistake I must have made in inputting our own parameters: https://z9pm.adj.st/?adjust_t=klm012&deeplink=myapp%3A%2F%2Fpage&fallback=https%3A%2F%2Ffallback.webpage

**Comment by lwa-moz** [comment]
Ok - Our Adjust rep forgot to include some notation in the template. Here's the correctly formatted link for our use: https://bhqf.adj.st/?adjust_t=6tteyjo&adj_deeplink=lockwise%3A%2F%2F&adj_fallback=https%3A%2F%2Fwww.mozilla.org%2Fen-US%2Ffirefox%2Flockwise

**Comment by ddurst** [comment]
Thank you @lwa-moz!

**Comment by lesleyjanenorton** [comment]
@lwa-moz thank you! Desktop issue is totally resolved with the new link but on mobile (iPhone XS Max with fresh Lockwise install) I'm being taken to the app store, instead of directly into the the app.

**Comment by SimonBasca** [comment]
Tested on iPhone X (13.2.2) on Lockwise 1.7.0 build 3092. Going to the https://monitor.firefox.com/, tapping on the bento menu and choosing Lockwise when:

- Lockwise is installed, the app will open
- Lockwise is not installed, tapping on the link will take me to the Lockwise app in App Store.

**Comment by lwa-moz** [comment]
> @lwa-moz thank you! Desktop issue is totally resolved with the new link but on mobile (iPhone XS Max with fresh Lockwise install) I'm being taken to the app store, instead of directly into the the app.

I'll check with Adjust - sounds like a bug. Only other reason would be if your test device OS is pre-iOS 9 (which seems unlikely).

**Comment by abodea** [comment]
After confirming with the team, I will close this issue as it was verified as fixed [above](https://github.com/mozilla-lockwise/lockwise-ios/issues/1100#issuecomment-558637166).

@lesleyjanenorton if you can still reproduce this please feel free to re-open the issue, also if you can confirm if everything is alright on your side, thanks.
