### ISSUE TITLE
Release 1.7.0

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockwise/lockwise-ios#1107]
Creating an issue to help us track the tasks/steps/work to release this point release.

**Comment by kaylagalway** [comment]
Three PI requests were created for this release:
https://jira.mozilla.com/browse/PI-380
https://jira.mozilla.com/browse/PI-382
https://jira.mozilla.com/browse/PI-386

There are currently no blocker bugs and we will be moving forward with release.
