### ISSUE TITLE
Login detail view header is white

### ISSUE THREAD

**Issue by isabelrios** [mozilla-lockwise/lockwise-ios#1113]
## Steps to reproduce
Login on iPad device
### Expected behavior
The view is correct
### Actual behavior
The login detail view header is all shown in white
### Device & build information
* Device: iPad Air
* Build version: ios13 branch bc3c7e1
### Notes
Attachments: 
![Screenshot 2019-11-07 at 15 27 34](https://user-images.githubusercontent.com/1897507/68407129-55337280-0183-11ea-88c0-863ca2c9bde7.png)

**Comment by abodea** [comment]
Verified as fixed using the latest build provided by Kayla **`3852`** with **`iPad Pro(12,9) iOS 13.1`**.
