### ISSUE TITLE
[iPad] crash on autofill onboarding screen

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-lockwise/lockwise-ios#1120]
## Steps to reproduce
1. Clean install Lockwise
2. Follow the welcome screen until you reach the autofill onboarding screen

### Actual behavior
* Lockwise will crash.

### Expected behavior
* Lockwise will not crash. 

### Device & build information
* Device: iPad Pro 3rd gen
* Build version: master branch build number 3809

### Notes
* Reproducible only on iPad
* Attachments: [Firefox Lockbox  11-11-19, 3-07 PM.crash.zip](https://github.com/mozilla-lockwise/lockwise-ios/files/3831427/Firefox.Lockbox.11-11-19.3-07.PM.crash.zip)

**Comment by kaylagalway** [comment]
Unable to reproduce this on an iPad Pro running on iOS 13.2. Just verified this build was produced on buddybuild with Xcode 11.2, which causes crashes on devices running earlier operating systems if the app attempts to load a storyboad generated page that contains a UITextView. The Autofill page contains a text view and would cause this crash.  

Creating a new build for testing with Xcode 11.2.1 to see if QA can still reproduce this issue.

**Comment by kaylagalway** [comment]
New build produced with Xcode 11.2.1 is master branch build [3820](https://dashboard.buddybuild.com/apps/5a0ddb736e19370001034f85/build/5dc9aaaa979f93000125fe38)

[Device Install Link](https://downloads.buddybuild.com/download/ios?buildID=5dc9aaaa979f93000125fe38&email=kayla.galway@gmail.com&download_token=15d62a64-4003-4a3e-9bbc-a60cb14b7abc)
[IPA Download Link](https://dashboard.buddybuild.com/api/download/get-ipa?buildID=5dc9aaaa979f93000125fe38&download_token=15d62a64-4003-4a3e-9bbc-a60cb14b7abc)

**Comment by SimonBasca** [comment]
This is no longer reproducible with the new build 3820. Test on iPad Pro 13.1 and iPad Air 3 12.4.
