### ISSUE TITLE
Spinning throttle is not visible because it's white on white background

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-lockwise/lockwise-ios#1121]
## Steps to reproduce
1. Clean install Lockwise 
2. Log in
3. After the login list is populated, pull down to refresh the list

### Expected behavior
* Spinning throttle should be a darker color
### Actual behavior
* Spinning throttle is not visible because it's white on white background
### Device & build information
* Device: iPhone X
* Build version: master branch build number 3809
### Notes
Attachments:

**Comment by kaylagalway** [comment]
Fix for this can be found in master branch build 3852.

[Install IPA on Device](https://downloads.buddybuild.com/download/ios?buildID=5dcc8d8fc52bf100017ba2f6&email=kayla.galway@gmail.com&download_token=9a38dbcd-b47e-494d-ba23-92d65f1d3181)

[Download IPA](https://dashboard.buddybuild.com/api/download/get-ipa?buildID=5dcc8d8fc52bf100017ba2f6&download_token=9a38dbcd-b47e-494d-ba23-92d65f1d3181)

**Comment by abodea** [comment]
Verified as fixed using the latest build provided by Kayla **`3852`** with **`iPhone X iOS 13.2.2`**.
Note that the spinning throttle is displayed correctly.
Based on my comment I will close this issue.
