### ISSUE TITLE
Keyboard is not dismissed when scrolling on the login list

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-lockwise/lockwise-ios#1123]
## Steps to reproduce
1. Launch Lockwise
2. Tap on the "Search logins"
3. Type a few letters from login
### Expected behavior
- When scrolling trough the search results the keyboard should dismiss to reveal the results from the bottom.
### Actual behavior
- The keyboard is not dismissed and thus the results from the bottom are not visible
### Device & build information
* Device: iPhone X
* Build version: master branch build number 3809
### Notes
Attachments: 
- [Video.MP4.zip](https://github.com/mozilla-lockwise/lockwise-ios/files/3831612/Video.MP4.zip)

**Comment by kaylagalway** [comment]
Fix for this can be found in master branch build 3852.

[Install IPA on Device](https://downloads.buddybuild.com/download/ios?buildID=5dcc8d8fc52bf100017ba2f6&email=kayla.galway@gmail.com&download_token=9a38dbcd-b47e-494d-ba23-92d65f1d3181)

[Download IPA](https://dashboard.buddybuild.com/api/download/get-ipa?buildID=5dcc8d8fc52bf100017ba2f6&download_token=9a38dbcd-b47e-494d-ba23-92d65f1d3181)

**Comment by abodea** [comment]
Verified as fixed using the latest build provided by Kayla **`3852`** with **`iPhone X iOS 13.2.2`**.
Based on my comment I will close this issue.
Thanks for the build @kaylagalway.
