### ISSUE TITLE
Auto fill button doesn’t work on iOS 12.2

### ISSUE THREAD

**Issue by hdnshare** [mozilla-lockwise/lockwise-ios#1145]
## Steps to reproduce
1. iOS version is 12.2.
2. Open Safari, go to Safari’s Private mode.
3. Go to a website login page, then the autofill button of Lockwise show up.
4. Tap the autofill button. Nothing happen.

### Expected behavior
Auto fill works after tap the auto fill button.
### Actual behavior
Nothing works after tap the auto fill button.
### Device & build information
* Device: iPhone 7
* Build version: iOS 12.2
* Lockwise version: 1.7.0
### Notes
The only way to make Lockwise work is: tap the key icon > Lockwise... > wait for Lockwise window to popup > search account, then tap account to auto fill.

**Comment by eliserichards** [comment]
Closing in favor of #1070 👍
