### ISSUE TITLE
No space between Cancel button label in Edit view and entry title

### ISSUE THREAD

**Issue by isabelrios** [mozilla-lockwise/lockwise-ios#1173]
## Steps to reproduce
Have an entry with long web address name
### Expected behavior
The Edit View UI looks fine
### Actual behavior
There is almost no space between Cancel button label and the entry title
### Device & build information
* Device: iPhone 8
* Build version: master 2514332
### Notes
Attachments: 
<img width="337" alt="Screenshot 2019-12-13 at 14 34 36" src="https://user-images.githubusercontent.com/1897507/70804130-00080380-1db6-11ea-8018-c59160046217.png">

cc UX expert here @changecourse

**Comment by changecourse** [comment]
Yes, my initial thought would be that we should trim the max character count (prior to truncation) from the view by 3-5 characters, though we'd have to look at it across different device views (so likely a percentage adjustment for the width of the title container)
