### ISSUE TITLE
Autofill Credential Provider does not show domain names when in dark mode

### ISSUE THREAD

**Issue by kaylagalway** [mozilla-lockwise/lockwise-ios#1182]
## Steps to reproduce
- On iPhone set phone to dark mode
- Attempt to autofill a credential and click the option to open lockwise and view credential list
- List will show only usernames and not domains

### Expected behavior
- You should be able to see domains when in dark mode

### Actual behavior
- You can not see domains in dark mode

**Comment by SimonBasca** [comment]
Verifying as fix on 1.7.2 (4059).
