### ISSUE TITLE
Login is not deleted after tapping delete button

### ISSUE THREAD

**Issue by vladbencovici** [mozilla-lockwise/lockwise-ios#1188]
Steps to reproduce:
1. Install Lockwise on an iOS device.
2. Login into Lockwise.
3. Tap on a saved login.
4. Tap "Delete Login' button.
5. Observe.

Expected behavior
The saved login should be deleted

Actual behavior
The saved login is not deleted after tapping the 'Delete Login' button

* Device: iPhone Xs Max; iPad Air 3
* Build version: Lockwise master branch v1.7.2 (4059)

**Comment by kaylagalway** [comment]
This issue is currently present in the production version of the app as well.

**Comment by vladbencovici** [comment]
Verified as fixed in v1.7.2 #4078
