### ISSUE TITLE
Startup crash on first launch

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-lockwise/lockwise-ios#1189]
## Steps to reproduce
1. Clean install Lockwise
2. Launch Lockwise
3. Tap "Skip" on the pop-up message
### Actual behavior
- Lockwise will crash.
### Device & build information
* Device: iPhone 7 (12.3.1)
* Build version: 1.7.2 (4059)
### Notes
- Not reproducible after first launc
- Not reproducible on iOS 13.3
Attachments: 
[RPReplay_Final1581078877.MP4.zip](https://github.com/mozilla-lockwise/lockwise-ios/files/4170777/RPReplay_Final1581078877.MP4.zip)

**Comment by SimonBasca** [comment]
Also experienced this on iPad with iOS 13.3.

[Firefox Lockbox  2-7-20, 5-47 PM.crash.zip](https://github.com/mozilla-lockwise/lockwise-ios/files/4171645/Firefox.Lockbox.2-7-20.5-47.PM.crash.zip)

**Comment by SimonBasca** [comment]
This issue is not reproducible on the App Store version 1.7.1 and neither on the latest TestFlight version 1.7.2 (4045). 

Also as a note, maybe it could help debug this issue, if I open version 1.7.2 (4059) without internet connection on first launch the crash will not occur after re-connecting to the internet.

**Comment by SimonBasca** [comment]
Oddly this doesn't seem to be reproducible on latest master d14e787c203 on the same device. My suggestion will be to leave it as it is and I can recheck it on the next release candidate. What do you think @kaylagalway ?

**Comment by kaylagalway** [comment]
Sounds good, thanks @SimonBasca !

**Comment by SimonBasca** [comment]
This issue is no longer reproducible on latest RC 1.7.2 (4078).
