### ISSUE TITLE
Lockwise is unusable after following the STR

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-lockwise/lockwise-ios#1190]
## Steps to reproduce
1. Login to FxA
2. Disconnect from FxA
3. Login to FxA
4. Close Lockwise from App Switcher
5. Re-open Lockwise 

### Actual behavior
- Lockwise is unusable.

### Device & build information
* Device: iPhone 7
* Build version: 1.7.2 (4059)
### Notes
- Possibly a regression from #1181
Attachments: 
[Lockwise unusable.mov.zip](https://github.com/mozilla-lockwise/lockwise-ios/files/4171212/Lockwise.unusable.mov.zip)

**Comment by SimonBasca** [comment]
This issue is no longer reproducible following the STR. Tested on iPhone 8 (13.3)

**Comment by isabelrios** [comment]
Just wanted to add that automated tests work fine now too. Thanks @kaylagalway !

**Comment by SimonBasca** [comment]
This issue is no longer reproducible following the STR on 1.7.2 (4078). Tested on iPhone 8 (13.3)
