### ISSUE TITLE
Lockwise block on purple screen during launch

### ISSUE THREAD

**Issue by narFnarF** [mozilla-lockwise/lockwise-ios#1201]
## Steps to reproduce
1. Launch Lockwise

### Expected behavior
List of password appears after a short loading

### Actual behavior
After the splash screen, the app blocks (soft lock) on a purple screen. Killing and relaunching the app doesn't help.

See screenshot below.

### Device & build information
* Device: iPhone 5s, latest OS (12.4.5)
* Build version: 1.7.2
### Notes
I don't even reach the part where Lockbox ask for my Touch ID. The app freezes before that.

Attachments: 
![](https://i.imgur.com/lvv1q5l.png)

**Comment by narFnarF** [comment]
Maybe similar with https://github.com/mozilla-lockwise/lockwise-ios/issues/1180 ?

**Comment by narFnarF** [comment]
After a few reboots, Lockwise eventually started the onboarding flow (where it presents its features, then as for Login). I went through the login flow (email, password, 2-factor auth). After succesful login, I reach the main screen (where we normally see the list of logins) but it was empty. There was only the message saying that I should use Firefox to enter passwords.

I tried to uninstalled and re-install the app as suggested in #1180. After login again, I now see my list of passwords. It seems to be working now.

**Comment by designakt** [comment]
Experienced the same after updating my OS to the latest on iPhone 6S and a following update of Lockwise. Deleting the app and starting over was the only thing that worked.

**Comment by bantern** [comment]
I am having this exact issue. When using Firefox for iOS, all passwords are visible through “Logins and Passwords”, but Lockwise opens to a blank purple screen.

**Comment by SimonBasca** [comment]
We were unable to reproduce this issue while testing v1.7.3(4110).
