### ISSUE TITLE
Wrong version number displayed in settings (1.7.2 instead of 1.7.3)

### ISSUE THREAD

**Issue by abodea** [mozilla-lockwise/lockwise-ios#1206]
## Steps to reproduce
1. Install and launch Lockwise.
2. Access the settings menu.
3. Observe the app version number.
### Expected behavior
The lockwise version number should be 1.7.3.
### Actual behavior
The lockwise version number is 1.7.2
### Device & build information
* Device: **iPhone X (13.3.1).**
* Build version: **1.7.3 (4110).**
### Notes
Attachments: 

![Screenshot 2020-04-09 at 16 46 34](https://user-images.githubusercontent.com/42831109/78902198-20a14b00-7a82-11ea-8f51-f137d2644643.png)

**Comment by kaylagalway** [comment]
I hadn't increased the version number in the info.plist of the version you tested. This PR handles that and should remedy the issue: https://github.com/mozilla-lockwise/lockwise-ios/pull/1204
