### ISSUE TITLE
String freeze and export for localization 

### ISSUE THREAD

**Issue by devinreams** [mozilla-lockwise/lockwise-ios#207]
Follow up from #89 and related to #204 

Depends on #440

- [X] define additional languages we plan to support: in addition to English, start to support German and French. Additional languages to come later as we get more community support in those regions
- [x] add support for those languages
- [x] bundle the strings files for translators
- [x] register project and upload to Pontoon

This is a post-launch todo so translation can happen _during_ Test Pilot experiment, not necessary before.

**Comment by sandysage** [comment]
Based on the app launch, I think we can start with the top 3 from the list @irrationalagent provided:

- [X] EN
- [ ] DE
- [ ] FR

This gets us significant coverage without needing to support every language right away. We can always expand on this list at a later time.

I'm also adding this note to the description above.

**Comment by devinreams** [comment]
Per @sandysage we will not do this until after all our content requirements get sorted out. Moving this and #440 back out of the backlog.

**Comment by devinreams** [comment]
Strings have frozen for the rebrand and are being exported via manual scripts documented in `docs`.

A big thanks to @joeyg for making it happen 🥇
