### ISSUE TITLE
"< Settings" action link on FAQ & Send Feedback screen adjustments for consistency

### ISSUE THREAD

**Issue by nickbrandt** [mozilla-lockwise/lockwise-ios#426]
Currently, the press state for the "< Settings" action link on the FAQ & Send Feedback screens is a bit lighter than the others (desired = #ffffff @ 60% opacity).

Also, this action link also transitions (slides left) into place, vs. other areas of the app we just have this link static on the left upon navigating to the screen. Ideally we would like this to be consistent with the others, and not transition upon reaching these screens.

**Comment by devinreams** [comment]
Thanks @nickbrandt. Some comments that may be helpful from #413 related to #251:

- Looks like the back ("< Settings") buttons for those screens are not being customized by us and are just iOS standard.
- Same with the navigation to go "< Back" when you tap the "Learn more" link on the Welcome screen, as its the same implementation of what we call the "StaticURLWebView".

**Comment by sandysage** [comment]
This appears to be addressed in the rebrand work. Closing.
