### ISSUE TITLE
Inform the user when the `passwords` collection is not being synced.

### ISSUE THREAD

**Issue by jhugman** [mozilla-lockwise/lockwise-ios#536]
Context: the user can chose which collections they want synced. If the `passwords` collection is not being synced, then Lockbox won't work.

From @nickalexander

> Lockbox should message when the "passwords" Sync 1.5 collection is not being synced.  That is, if a user's Sync 1.5 account is healthy, but the meta/global record doesn't enable "passwords", then Lockbox should message as much.  (In this case Lockbox actually could remotely enable syncing passwords, but I think that's a lot of risk that you probably don't want to sign up to test.)
>
> To test this situation, connect Lockbox to an existing Sync 1.5 account.  Have a different client (they all support this behaviour) disable syncing "passwords" (called "Logins" everywhere, I think).  You'll probably find that Lockbox thinks everything is fine -- and from Sync 1.5's perspective, it is.  But you'll suddenly have no data locally, since the Sync 1.5 code you're using recognizes this situation and wipes the local collection.  (Sync 1.5's model is that there's one setting for "am I syncing this datatype" for the whole device constellation; it's not per-device.)
>
> Concretely, we need to ensure that _something_ checks that "passwords" is enabled in meta/global and exposes that to Lockbox.  One way to achieve that might be to expand `SyncError` to include `PasswordsCollectionDisabled`, and then to use the `reasonToNotSync` function to bubble up the error to Lockbox.  I don't see a low-impact way to do this, since by necessity it spans the two active code bases.

### Visual Design

**InVision**
No Entries (during initial sync): https://mozilla.invisionapp.com/share/BQEUSO0S2#/311886423_Logins_Not_Set_To_Sync_-_No_Entries
Has Entries (after initial sync): http://mozilla.invisionapp.com/share/BQEUSO0S2#/311886422_Logins_Not_Set_To_Sync_-_With_Entries

**Zeplin**
No Entries (during initial sync): https://zpl.io/a8KAL06
Has Entries (after initial sync): https://zpl.io/VYByegk

Note: The "Show me how" and "Learn more" links would direct to the FAQ, specifically the "How do I enable sync on Firefox?" section. (https://lockbox.firefox.com/faq.html#how-do-i-enable-sync-on-firefox)

**Comment by sandysage** [comment]
@changecourse @nickbrandt If someone disables logins sync, then nothing shows up in Lockbox. Based on the description here, we can detect that case. 

We'll want to provide clear messaging to users about why they're not seeing passwords (don't have logins sync enabled) and what they can do to fix it (turn on logins sync). Moved to the blocked column to provide the UI revisions before moving it to the backlog.

**Comment by nickbrandt** [comment]
@jhugman a questions related to this:

I would assume a common use case for this would be when a user is first syncing their entries. However, I understand that this could also happen after a user already has entries in their list and then turns off syncing logins at a later time. In this case, would the user still have access to the logins they had already synced, or would they be become unavailable?

**Comment by sashei** [comment]
@nickbrandt the user would still have access to the logins that had already been synced in this case.

**Comment by sashei** [comment]
We also will have a way to detect that the user has disabled the passwords collection from the account side, if we want to display explicit messaging around this.

**Comment by nickbrandt** [comment]
@sashei Gotcha, thanks for letting me know

**Comment by sandysage** [comment]
Closing in favor of #543
