### ISSUE TITLE
Set up universal linking to catch redirects

### ISSUE THREAD

**Issue by sashei** [mozilla-lockwise/lockwise-ios#62]
per conversation on https://github.com/mozilla-lockbox/lockbox-ios/pull/52

Apple Documentation:  https://developer.apple.com/library/content/documentation/General/Conceptual/AppSearch/UniversalLinks.html

**Comment by devinreams** [comment]
We now know for certain can add content to the `.well-known` directory:

https://github.com/mozilla-lockbox/mozilla-lockbox.github.io/tree/master/.well-known

https://mozilla-lockbox.github.io/.well-known/test.txt

**Comment by sashei** [comment]
Closing this in favor of #554.
