### ISSUE TITLE
"No matching entries" after Disconnect/Reconnect

### ISSUE THREAD

**Issue by csuciu** [mozilla-lockwise/lockwise-ios#653]
iPhone x (11.4.1)
Lockbox 1.2 (2018)

1. Clean install Lockbox.
2. Sign in with valid credentials.
       => First sync ends successfully and the logins list gets populated.
3. Go to Lockbox settings => "Account" and hit "Disconnect".
4. Reconnect.

Result: "No matching entries".

**Comment by devinreams** [comment]
Thanks, this appears related to or the same as #592

**Comment by sandysage** [comment]
This appears to be addressed. Closing.
