### ISSUE TITLE
The picture and display name of the previous sign in are displayed in the "Account" page for a newly created FxA

### ISSUE THREAD

**Issue by csuciu** [mozilla-lockwise/lockwise-ios#655]
iPhone X (11.4.1)
Lockbox 11.2 (2018)

1. Have Lockbox freshly installed.
2. Sign in with an account that has a picture and a display name set.
3. Disconnect.
4. Follow the sign up steps in Lockbox and create a new account.
5. Confirm the new account then go to Lockbox settings => "Account"

Result: The picture and the display name of the previously signed in account are displayed in the "Account" page for the newly created account.

**Comment by devinreams** [comment]
Thanks @csuciu I can confirm this. Likely related to the not-quite-disconnecting being resolved as part of:

- #653 
- #592 
- #641 

(Don’t mind me, I’m just linking related things up here)

**Comment by SimonBasca** [comment]
This issue is no longer reproducible in v1.5.0 build 3240.
