### ISSUE TITLE
Consider logging test client_ids and excluding them from Telemetry queries

### ISSUE THREAD

**Issue by devinreams** [mozilla-lockwise/lockwise-ios#695]
We do a lot of testing and use the app a bit which sends Telemetry data.

We should consider gathering up some of our client_ids being used for testing so @irrationalagent can exclude them from all our reporting and queries.

**Comment by sandysage** [comment]
@irrationalagent is this still a concern for us? Do we think our testing has any real impact on our current metrics?

**Comment by irrationalagent** [comment]
I think we've passed the point where our test devices are within the daily margin of error here
