### ISSUE TITLE
Get Started screen is shown twice

### ISSUE THREAD

**Issue by isabelrios** [mozilla-lockwise/lockwise-ios#698]
I don't have clear steps to reproduce this but looks like it happens randomly when closing and opening the app again. Please see video: https://youtu.be/pdVD1yhUYig (sorry for the bad quality) 
Steps
Tap on Get started button

Actual
The same Get started screen is shown, it is necessary to tap on Get Started again

**Comment by devinreams** [comment]
Thanks for filing this. I see this happen when signing in sometimes too and wonder if its a symptom or related to disconnecting/reconnecting like at #592

**Comment by isabelrios** [comment]
Yes, I should have mention that, it is when closing/opening after disconnecting the account, while connecting again (type email for example and close the app)...

**Comment by SimonBasca** [comment]
I tried different scenarios also those mentioned by Isable but was unable to reproduce this issue in v1.5.0 build 3240. I will keep an eye out for this and re-open this issue is encountered again.
