### ISSUE TITLE
After uninstall the app autofill is not working unless app is configured again in settings

### ISSUE THREAD

**Issue by isabelrios** [mozilla-lockwise/lockwise-ios#729]
This might not be a common scenario but it is important to know that's happening to avoid it when updating the app (if it could happen there, trying to repro...)
**Preconditions**
- Lockbox installed from master 8a8d6c4, configured to use autofill
- Received new version 1.3 from TF

**Steps**
- Install the app from TF
- Open a web site with credentials stored

**Actual**
The Autofill screen is not shown.
The credentials list is not shown for the website.

So, what seems to be happening is that since for the first build I had configured Autofill settings, and it was working, when I re-installed the newer version, the Lockbox app appeared already marked in Autofill Passwords automatically but it was not "updated", so whenever I go to a website, the credentials list does not appear.
![image](https://user-images.githubusercontent.com/1897507/45544632-238d7880-b818-11e8-906e-c320e348a3e7.png)

In order to make the autofill working I had to unselect and select the app again in that screen and wait for the lockbox app to be updated.

**Expected**
If the Lockbox app is configured in settings, the credentials should be shown

As I said this might not be a use case since it is not common to uninstall the app from an user point of view, but it could happen and the feeling is that autofill does not work

**Comment by sashei** [comment]
My feeling is that if this is an issue for _upgrading_, we should prioritize and fix, otherwise I don't think it's expected that uninstalling + reinstalling will maintain the autofill suggestions.

**Comment by SimonBasca** [comment]
Verifying as fix on v1.5.0 build 3240. Tried the following scenarios:

- Downgrade from v1.5.0 (3240) to 1.4.0 (2908) and again upgrade to v1.5.0 (3240). Autofill is working correctly.
- Downgrade from v1.5.0 (3240) to 1.4.1 (2943) and again upgrade to v1.5.0 (3240). Autofill is working correctly.

If there are any more scenarios to cover please let me know. For know I think this can be closed as verified - fixed.
