### ISSUE TITLE
Alert user of new AutoFill feature on opening the app after update

### ISSUE THREAD

**Issue by nickbrandt** [mozilla-lockwise/lockwise-ios#733]
In order to make current Lockbox users aware of the new AutoFill feature, we need to notify them once they have updated to this version.

_note: this is an enhancement and not required for the AutoFill feature submission_

**Comment by sandysage** [comment]
I would say this is no longer relevant. All new installs will see the autofill feature onboarding. We can one day consider what it means to provide more contextual references/highlights/in-product onboarding.
