### ISSUE TITLE
Returning to a non-locked external web view (i.e., FAQ) will lock while app is the foreground

### ISSUE THREAD

**Issue by sashei** [mozilla-lockwise/lockwise-ios#735]
steps to reproduce:
- set autolocktime to 1min (for convenienc)
- open an FAQ or feedback page
- background app in <1min
- foreground app
- wait 1min

expected: app remains unlocked
actual: app locks after 1min

**Comment by sandysage** [comment]
I think this is expected behavior. Closing in favor of keeping what we have.
