### ISSUE TITLE
In autofill, clicking search immediately dismisses the keyboard

### ISSUE THREAD

**Issue by linuxwolf** [mozilla-lockwise/lockwise-ios#738]
When using autofill and viewing the list of entries, clicking on the search causes the keyboard to flash - it starts to open then is immediately dismissed.  Clicking on search a second time brings up the keyboard as expected.

This occurs on an iPad Pro in both landscape and portrait layouts. Only happens when you are viewing credential list from an app.

@nickbrandt only had this occur on apps where he had an associated entry. When there were no matching entries, search opened keyboard on first tap.

**Comment by devinreams** [comment]
@linuxwolf @nickbrandt can you please retry this keyboard flash with the build distributed through TestFlight just now?

I tried on my iPhone X and iPad Pro (in Safari using the AutoFill "search") and the updated search UI does not flash the keyboard up and away (it persists on screen).
