### ISSUE TITLE
Blank screen when using Lockbox from BBC news app

### ISSUE THREAD

**Issue by joewalker** [mozilla-lockwise/lockwise-ios#794]
STR:
You'll need a BBC account and to have saved your username/password in sync. (You might need to be in the UK)

1. Install https://itunes.apple.com/us/app/bbc-news/id364147881
2. Click on a link that contains a Video.
3. "You'll need to sign in..." Click Sign in
4. Above the keyboard area "Passwords", "Lockbox..."
5. Lockbox appears, says "Sign in required" and pops up the Touch ID dialog. activate Touch ID
6. White screen of death. (Will attach screenshot)

![image](https://user-images.githubusercontent.com/76258/47877032-c9ba2f80-de12-11e8-95e2-ed980e4729e8.png)

**Comment by SimonBasca** [comment]
Verifying as fix on v1.5.0 build (3240).
