### ISSUE TITLE
User is signed out after tapping on Lock Now option (after some previous steps)

### ISSUE THREAD

**Issue by isabelrios** [mozilla-lockwise/lockwise-ios#801]
Reproducible with latest TF build: 1.3.2 (2635), iOS 12, iPhone 6s, iPod Touch

Steps
1-Install the app or update it.
2-Sign in with a valid account
3-Change the Auto Lock setting to 1 minute
4-Tap on Lock Now
5-When trying to Unlock the device (Touch ID or passcode) fail at least once to unlock, then unlock the app successfully
6-Repeat from step 4 several times

Actual
The user is signed out when the app is locked. Sometimes you need to repeat the steps three or more times but some others it happens when introducing the ID or passcode incorrectly just once.

Expected
User should not be signed out. Please notice that once this issue is seen and the account signed out, after login again when locking the app using the Lock Now option in settings it will always disconnect the account.

Please see video:
https://youtu.be/LrHY59X1jYk

**Comment by lorenzhs** [comment]
So I just had this happen to me (I think) but I wasn't *really* signed out. After I got the welcome screen for new users, I closed the app (swipe gesture in app switcher) and when I opened it again, I could just unlock it. So maybe this could be a UI state problem instead of an actual sign-out.

**Comment by devinreams** [comment]
Thanks so much for your report @lorenzhs. This is helpful for us to try and reproduce and troubleshoot ourselves.

**Comment by SimonBasca** [comment]
Verifying as fix on v1.5.0 build (3240). The issue is no longer reproducible after following the STR.
