### ISSUE TITLE
[iOS 12.x] "Set Passcode" button directs to wrong screen because Apple doesn't provide a way to link directly

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-lockwise/lockwise-ios#803]
Build: 1.3.2
Device: iPhone 7
iOS: 12.0 

Preconditions:
- Passcode/Touch ID disabled from iOS Settings
- Clean install

Steps to reproduce:
1.  On a clean install, launch Locbox
2.  Tap on the "Get Started" button
3. When prompted to use passcode, tap "Set Passcode"

Actual results:
- User is directed to the wrong screen in iOS Settings.

**Comment by SimonBasca** [comment]
@joeyg after step 3) on iOS 12.0, I am redirected to this screen (see attached screenshot). On iOS 11.x it redirects to the main settings screen. 

![screen shot 2018-11-07 at 9 03 37 am](https://user-images.githubusercontent.com/32130829/48115632-3d719780-e26c-11e8-96b0-357eb5fabcd1.png)

**Comment by joeyg** [comment]
@sandysage given the trouble linking directly to settings screens what is the recommendation for this issue?

**Comment by sandysage** [comment]
Let's remove the link given the limitation with directly linking to the settings screen.

**Comment by sashei** [comment]
@changecourse @sandysage do we know what content we want as confirmation instead of "Set Passcode"?

**Comment by sandysage** [comment]
I think the only call to action we can do here is "dismiss". @changecourse let me know if you have other considerations. Otherwise, let's plan to move forward with the one call to action.
