### ISSUE TITLE
The loading circle bar is still displayed in entries list after a lock button interrupt 

### ISSUE THREAD

**Issue by abodea** [mozilla-lockwise/lockwise-ios#837]
## Steps to reproduce
1. Launch Lockbox.
2. Login with valid credentials.
3. Reach the entries menu.
4. Refresh the entries and lock the screen.

### Expected behavior

The entries list should refresh after unlocking the device.
### Actual behavior

The loading circle bar is still displayed/loading, the entries list is not refreshed and a big space is displayed between loading circle bar and search your entries field.

### Device information
Build: 1.3.3
Device: iPhone XR 
iOS: 12.0

### Notes
Note that the screen can be refreshed only after performing an app restart.
For more details please see the [video](https://goo.gl/c2vpKc).

**Comment by joeyg** [comment]
@abodea do you know if this happened in the previous version of the app (1.3.2)?

**Comment by abodea** [comment]
@joeyg yes this issue can be reproduced on previous version like (1.3.2).

**Comment by SimonBasca** [comment]
Verifying as fix on v1.5.0 build (3240).
