### ISSUE TITLE
Sign-in Required notification when I'm likely already signed in

### ISSUE THREAD

**Issue by jdragojevic** [mozilla-lockwise/lockwise-ios#863]
Lockbox on iOS

1. Open a website that requires authentication
2. Go to their sign-in screen
3. Click in the username field
4. click on the 🔑 Passwords for lockbox
Result Sign in Required popup displayed.  See image.

![image](https://user-images.githubusercontent.com/299270/51561496-6a8a1b00-1e55-11e9-8160-6e7eba80700f.png)

1. Click OK in the dialog
Result: returned back to website's sign-in form, but the form is now not-responsive.
I have to close the browser and reopen to the page.

On second attempt, when I open Lockbox to get the password, there is no dialog and it works as expected.

@devinreams @sandysage 

This has been happening for at least 2 weeks. But I'm not sure when it started, I've only recently started using lockbox.

**Comment by SimonBasca** [comment]
Verifying as fix on v1.5.0 build (3240).
