### ISSUE TITLE
Rebrand to Lockwise

### ISSUE THREAD

**Issue by changecourse** [mozilla-lockwise/lockwise-ios#921]
To replace assets in lockbox-ios/Common/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json

[Lockwise_appicon.zip](https://github.com/mozilla-lockbox/lockbox-ios/files/3104168/Lockwise_appicon.zip)

Rollout plan: https://docs.google.com/document/d/1U-Rqu4WZAYrLbwPeTM8F32Zwg67ymEq9CSRjhQ2w2Ec/edit

**Comment by devinreams** [comment]
In progress branch is started at:
https://github.com/mozilla-lockwise/lockwise-ios/tree/921-rebrand
