### ISSUE TITLE
User agent is not displayed in Firefox Account on desktop

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-lockwise/lockwise-ios#930]
Build: 1.5.0
Device: iPhone 7
iOS: 12.1

Preconditions:
- Log in to FxA on desktop and lockbox iOS

Steps to reproduce:
1. On desktop, go to the account management page 
2. Tap on Devices

Actual results:
- The user agent for Lockbox is not displayed. 

Note:
- Might be and FxA issue. 

<img width="525" alt="Screen Shot 2019-04-24 at 12 19 21" src="https://user-images.githubusercontent.com/32130829/56650061-f7c85000-668e-11e9-9334-944c04bdec0c.png">

**Comment by sashei** [comment]
@rfk do you have any insight on this?

**Comment by linuxwolf** [comment]
cc @vladikoff @eoger 
maybe we need to explicitly register a device?

**Comment by vladikoff** [comment]
this version still uses the old way to login right? I don't think device registration will solve the problem here. migrating to the OAuth login will fix this a bit, it will show a connected app

**Comment by sashei** [comment]
Hm, so it's possible that this will be resolved by using the `MozillaAppServices.framework` version of logging in. I thought `FxAClient.framework` was doing this appropriately though.

**Comment by rfk** [comment]
Lockbox is doing this correctly, this is a problem with the FxA "devices and apps" list; Let's track it over in https://github.com/mozilla/fxa/issues/946
