### ISSUE TITLE
Delete an entry from the entry edit view

### ISSUE THREAD

**Issue by sashei** [mozilla-lockwise/lockwise-ios#938]
## Requirements
* Should provide the ability to delete from the entry editing view
* Deleting the entry routes back to the list view

Depends on #937 

## Visual Design
**InVision**
Entry Detail - Edit: https://mozilla.invisionapp.com/share/BQEUSO0S2#/screens/347184546

**Zeplin**
Entry Detail - Edit: https://app.zeplin.io/project/5a4e9ff8032d0923200a2635/screen/5c6dc07d1380fe4628cb6cc4

**Comment by joeyg** [comment]
@devinreams @sandysage Should this be closed now that #1072 landed?

**Comment by devinreams** [comment]
>Should this be closed now ...

It should close automagically once the code lands on the default (`master`) branch. ✨
