### ISSUE TITLE
Deletion confirmation dialog  (confirm user wants to delete)

### ISSUE THREAD

**Issue by sashei** [mozilla-lockwise/lockwise-ios#939]
## Requirements
* Should have a disclaimer that I have to confirm when deleting a record from the entry edit view
* Should have ability to cancel the delete request

Depends on #937 
Depends on #938 

## Visual Design
**InVision**
Entry Detail - Confirm Delete: https://mozilla.invisionapp.com/share/BQEUSO0S2#/289206366_Entry_Detail_-_Edit_-_Confirm_Delete

**Zeplin**
Entry Detail - Confirm Delete: https://app.zeplin.io/project/5a4e9ff8032d0923200a2635/screen/5c6dc07d959ef19a21360492

**Comment by joeyg** [comment]
Can you delete from the Autofill screen or just from the main app?

**Comment by changecourse** [comment]
Good call-out... my assumption would be that no CUD tasks should be able to be performed from the autofill flow. Worth adding to the Requirements for each of the issues.

**Comment by SimonBasca** [comment]
Verifying as fix on build 3871. The delete confirmation dialog is correctly displayed and functional after swiping to delete a login entry.
