### ISSUE TITLE
Deletion confirmation toast (confirm user did successfully delete)

### ISSUE THREAD

**Issue by sashei** [mozilla-lockwise/lockwise-ios#940]
## Requirements
* Should display toast to confirm deletion on returning to entry list

Depends on #937 
Depends on #938 

## Visual Design
**InVision**
https://mozilla.invisionapp.com/share/BQEUSO0S2#/screens/347184556

**Zeplin**
https://app.zeplin.io/project/5a4e9ff8032d0923200a2635/screen/5c6dc07d911176464c071b75

Icons:
https://design.firefox.com/icons/viewer/#
[blob:https://design.firefox.com/470e7515-9d34-ed4b-a8eb-1e822fb0f7bf]

**Comment by sashei** [comment]
@changecourse I filed this issue because it was listed in the requirements epic #175, but looking at the iOS designs I haven't been able to find a toast. Do we want to have one, and if so what should it look like?

**Comment by joeyg** [comment]
@sandysage Is this the toast for this task? https://mozilla.invisionapp.com/share/BQEUSO0S2#/screens/347184556

**Comment by sandysage** [comment]
Holy moly! That's the dialog we want :). Thanks for finding it @joeyg

**Comment by joeyg** [comment]
@sandysage do you know where I can get the trash can icon?

**Comment by devinreams** [comment]
>do you know where I can get the trash can icon?

@joeyg "Delete" icon from our Photon design system: https://design.firefox.com/icons/

[blob:https://design.firefox.com/470e7515-9d34-ed4b-a8eb-1e822fb0f7bf](blob:https://design.firefox.com/470e7515-9d34-ed4b-a8eb-1e822fb0f7bf)

**Comment by changecourse** [comment]
[delete.zip](https://github.com/mozilla-lockwise/lockwise-ios/files/3282569/delete.zip)

I'll do ya one better :)

**Comment by SimonBasca** [comment]
Verifying as fix on build 3871. The toast is correctly displayed after deleting a login entry.
