### ISSUE TITLE
Lockbox 1.5.0 only shows a blue screen

### ISSUE THREAD

**Issue by past** [mozilla-lockwise/lockwise-ios#950]
Ever since the update to 1.5.0 I can't get Lockbox to work. The first update was crashing, but the last couple of versions just resulted in a blue screen after startup. Currently (build 3135) cold opening the app from the home screen goes from the splash screen to a blue page, without an unlock prompt or anything else. Starting from an autofill flow I see the correct header (cancel button, app name and search box), but an empty white space where the account list would appear.

**Comment by sashei** [comment]
@past thanks for reporting! what version of iOS are you running? does uninstalling + reinstalling the app resolve things for you?

**Comment by past** [comment]
I have iOS 12.2 and I was holding off on reinstalling in case there are useful diagnostic steps that I could take. Should I just go ahead and do it then?

**Comment by sashei** [comment]
@past it's very difficult for us to extract logs on builds released via testflight if they're not actively crashing :( I'd love to get the answers to a few more questions, but beyond that, I'd go ahead + reinstall to let you get your passwords again. We can do our best to test the upgrade path from this issue, and may get in touch with you again if I can't reproduce it!

The questions:
- Does hard quitting (via the app switcher) resolve your blue screen issue?
- Did you have the previous _Testflight_ release installed before updating to 1.5.0, or the previous iTunes store release?
- Which iPhone do you have?

Thanks so much again for letting us know about this issue!

**Comment by past** [comment]
Hard quitting doesn’t help, I have an iPhone 7 and I’ve been using the TestFlight releases since the beginning. Prior to 1.5.0 things were working fine.

**Comment by devinreams** [comment]
I've been testing on buddybuild Build 2943 (1.4.1 in production) directly up to the latest 1.5.0 build (3142) instead of taking of any of the in-between 1.5.0 builds (in case we had a bug or bad data state in between) and cannot reproduce this state.

This included a mixture of upgrading the app which data store was locked, autofill was enabled and not, etc.

@sashei I don't know where and when the blue screen itself was introduced but where/why does that exist and may it be part of the cause? I don't see it on 1.4.1 so it's [new-ish](https://github.com/mozilla-lockbox/lockbox-ios/compare/1.4.1.2943...master), right?

**Comment by devinreams** [comment]
From the production branch on buddybuild:

- installed build 2945 and signed in, locked
- upgraded to build 3005, unlocked (didn't see blue screen at all?) ✅ and then re-locked
- upgraded to build 3093, unlocked (didn't see blue screen at all?) ✅ and then re-locked
- upgraded to build 3138, stuck on a blue screen for ~2 ⚠️ seconds but then unlocked ✅

So something is maybe introduced between 3138 (97e80d7) and 3093 (2fe6527) from what minor quasi-reproduce I experienced? https://github.com/mozilla-lockbox/lockbox-ios/compare/97e80d7...2fe6527 so possibly around PR #936?

**Comment by sashei** [comment]
@devinreams the blue screen is a "holding" screen -- it likely existed in previous versions but something about the sync / datastore startup is slower now so I've seen it pop up slightly more frequently with the logins change.

**Comment by sandysage** [comment]
Justin O'Kelly encountered this issue on iOS 12.2 on iphone 8. Not sure which version of app via TestFlight before the update.

**Comment by sandysage** [comment]
Another report of this blue screen. Not sure which version was had previously, but it would have been from a couple of months ago (much older version) to the latest via TestFlight. Uninstalling Lockbox and reinstalling via TestFlight works fine. I realize this probably isn't helpful, but just want to capture that there are still instances of this occurring.

**Comment by lorenzhs** [comment]
Just got this from the App Store 1.5.0 release after upgrading from 1.4.1 (also App Store release). Anything I can do to help?

**Comment by natolh** [comment]
Same here with the latest App Store 1.5.0 release on iPhone 5S / iOS 12.3. Blue screen. Hard quitting does not change anything, desabling autofilll does not change anything, re-enabling it brings an update screen that last forever. Plus using autofill from Safari brings an empty view for selecting password. Lockbox is unusable.

**Comment by sashei** [comment]
@lorenzhs @natolh thank you for reporting, investigating now....

**Comment by lorenzhs** [comment]
In case it may be related, I had some issues with weird database state in the past (#815). I'll try updating on my iPad later, on which I set up lockbox much later (initial version was 1.4.1) and never had any issues.

**Comment by sashei** [comment]
@lorenzhs @natolh this is a weird question, but if you disconnect your device from the internet / mobile data and cold start Lockbox, do you move past the blue screen?

**Comment by natolh** [comment]
@sashei unfortunately I cannot test that. As the blue screen was quite an issue for me, I've tried to re-install Lockbox and... now it works ! 🙃

**Comment by lorenzhs** [comment]
@sashei I do. In airplane mode, it goes straight to an empty password list.

**Comment by lorenzhs** [comment]
I pressed "lock now" to try what would happen and now I get the unlock screen, but nothing happens when I press the unlock button, regardless of whether I'm connected to the internet.

**Comment by sashei** [comment]
@lorenzhs that's super useful, thank you so much. I think the problem will resolve itself if you disconnect your account in the offline state, turn the internet back on, and log in again. I really appreciate you debugging this with me!

**Comment by sashei** [comment]
@lorenzhs you may need to hard-quit the app to get back to the empty entry list?

**Comment by devinreams** [comment]
@lorenzhs @natolh thanks for your reports and help here, we really appreciate it.

If you’d like to receive beta builds in the future, or even test the patch @sashei just pushed, you can opt in through TestFlight: https://testflight.apple.com/join/AoGdcFaW

Thanks again ❤️

**Comment by lorenzhs** [comment]
@sashei disconnecting and reconnecting worked on the iPad (which exhibited the same behaviour), albeit only on the second attempt. On the iPhone, I can’t get past the unlock screen no matter what.
