### ISSUE TITLE
Lockbox incorrectly assumes its not logged in, hijacks screen and breaks original app that launched it

### ISSUE THREAD

**Issue by duoi** [mozilla-lockwise/lockwise-ios#953]
When lockbox is not authed,  immediately on launch it displays the pop up message saying it must be logged in first. If the "ok" button isn't pressed, it eventually does the Face ID recognition and logs in, but the popup is still there. If you press "ok", it closes lockbox but goes back to an unusable version of the original app that opened it.

I'm able to recreate it quite easily and this happens constantly. It stopped happening for a while and came back again recently.

I have a video I can share privately of the entire workflow in producing the bug.

**Comment by devinreams** [comment]
@duoi thanks for the report. To be clear: this is happening exclusively when launching the autofill feature, right?

Please feel free to email me anything else you can share privately to this username at mozilla dot com and thanks again 😁

**Comment by duoi** [comment]
All good. I emailed you a video. It has some of my logins so please keep it as private as possible.

I use Lockbox exclusively with and for the autofill feature. I opened the app directly for the first time in n number of months and it didn't appear to give me that prompt.

Cheers

**Comment by devinreams** [comment]
Thanks again for the report and video @duoi. 

If you're able and willing, we have a fix on the way via TestFlight to beta test before we release some time next week. You can opt-in here: https://testflight.apple.com/join/AoGdcFaW

**Comment by duoi** [comment]
It's not easily reproducible for me. It's just that when it happens, it happens, and continues to happen until I'm forced to reauth. It has happened twice so far - I've been using the app for about four-ish months.
