### ISSUE TITLE
Autofill only fills sometimes on 1.5.0

### ISSUE THREAD

**Issue by devinreams** [mozilla-lockwise/lockwise-ios#954]
Seems I'm encountering two things with 1.5.0 now:

1. after first setup and run with the app and system settings, the app fills nicely. but after backgrounding and letting it sit a while (maybe background crash?) then the autofill keyboard bar does show matching credentials, but tapping it _does not fill_ in the fields

2. after tapping the autofill entry in the keyboard bar once or a few times, autofill seems to crash or lose its data entirely and I don't see autofill matches on the keyboard bar again

**Comment by devinreams** [comment]
I found that maybe related to 1 is my very first autofill attempt does a long attempt to fill, but then silently crashes or doesn't fill.

If I tap out and back to the field the keyboard no longer shows matching autofill entries, just the generic "Passwords" button. Which then does open the autofill screen and fill in the fields when an item is selected.

But from there forward, it seems the autofill store is empty and never shows me matching entries in the keyboard again. If I disable and re-enable autofill in system settings, then it seems to populate and show the matching entries again. But I reproduce this same loop...

**Comment by sashei** [comment]
Update on this ticket: Definitely broken, definitely related to some of the lifecycle interactions in the autofill service. Spent a while hacking on this on Friday, going to circle back around following the rebrand work but believe I have an idea of where to fix!!
