### ISSUE TITLE
Autofill does not prompt for biometrics when Lockbox is locked

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-lockwise/lockwise-ios#976]
Build: 1.5.0 ( 3240)
Device: iPhone XR
iOS: 12.2

Preconditions:
- Autofill enabled
- Lock Lockbox from Settings

Steps to reproduce:
1. In Firefox or any browser or app, go to a login form
2. Tap on Username field 
3. Tap on the 'Passwords' button above the keyboard

Actual results:
- Lockbox will not prompt for bio metrics. 
- Opening Lockbox after following the STR will not prompt for biometrics.

**Comment by sashei** [comment]
@changecourse @linuxwolf @sandysage @devinreams soo this is happening by design... I don't remember our exact reasoning but I suspect it had something to do with user convenience. I think there's an argument to be made for having iOS autofill respect the app locked status, but what do y'all think?
