### ISSUE TITLE
Biometrics are not promoted after disabling and enabling Autofill

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-lockwise/lockwise-ios#977]
Build: 1.5.0 ( 3240)
Device: iPhone XR
iOS: 12.2

Preconditions:
- Autofill enabled
- Lock Lockbox from Settings
- Close Lockbox from app switcher

STR:
1. Go to iOS AutoFill Passwords in iOS Settings
2. Disable Autofill
3. Enable Autofill for Lockbox
4. Open Lockbox

Actual results:
- Lockbox is unlocked without biometrics.

[RPReplay_Final1557843446 2.mp4.zip](https://github.com/mozilla-lockwise/lockwise-ios/files/3178211/RPReplay_Final1557843446.2.mp4.zip)

**Comment by sashei** [comment]
This is related to the issues I bring up in the comment section of #976. I'd like to have a larger conversation about how autofill interacts with locking on iOS.
