### ISSUE TITLE
Fix remaining Lockbox strings

### ISSUE THREAD

**Issue by Pike** [mozilla-lockwise/lockwise-ios#991]
While setting up Lockwise iOS for localization, we found a few remaining occurrences of "Lockbox", some in UI, some in a11y, some in comments.

It'd be nice if we could get a fix for those before we expose strings for real.

You can search https://github.com/mozilla-l10n/lockwiseios-l10n/blob/5d9ab487f805536ebe9d9fd003ce783009a103c0/templates/lockwise-ios.xliff for examples.

https://github.com/mozilla-lockwise/lockwise-ios/blob/e64edee308d0a8f37153f17199f2df1d70cac8f9/CredentialProvider/Storyboard/Base.lproj/CredentialWelcome.storyboard#L46 shows that this is at least in spots still happening.

I invented the "blocks-l10n" label for issues like this.

CC @Delphine @devinreams

**Comment by devinreams** [comment]
@sashei @sandysage can we please promote these changes into the current sprint that’s being planned/started today?
