### ISSUE TITLE
Postmortem for "Blue screen of Death"

### ISSUE THREAD

**Issue by sashei** [mozilla-lockwise/lockwise-ios#994]
We released v1.5.0 with a critical error impacting a non-trivial portion of users, outlined at #950. This issue tracks critically reflecting on the following points:

- The root cause for the issue
- Our response + mitigation strategy
- Why we didn't catch it earlier
- Steps we are taking to ensure it doesn't happen again

**Comment by devinreams** [comment]
Met, documented and shared privately via @sashei (internal to Mozilla only):
https://docs.google.com/document/d/1UV5Zlo2DEkT3HK7Y90dqZMRSWjJ4S39aLaGi8c8ioUU/edit?usp=sharing

Follow-up to be scheduled to check on status of action items.

**Comment by devinreams** [comment]
All actions reviewed and completed and updated in the doc. ✅
